### ISSUE TITLE
Azure Databricks Version

### ISSUE THREAD

**Issue by chris-utter** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#106]
Lab 03 > Exercise 2 > Task 3 > References Runtime: 6.3 (Scala 2.11, Spark 2.4.4)
That runtime option no longer exists

**Comment by datarelish** [comment]
Did anyone get assigned to this issue?

**Comment by davidcwalls** [comment]
This issue is going to keep arising, e.g. https://github.com/MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution/issues/35

It seems like using the default version would require the least future maintenance and is pretty unlikely to cause any issues.  If not, switching to an LTS version should increase the length of time before requiring the next change.

**Comment by ctesta-oneillmsft** [comment]
runtime references have been updated in the manual and lab
