### ISSUE TITLE
Lab 2 Ex 2 - Why RA_GRS rather than LRS?

### ISSUE THREAD

**Issue by davidcwalls** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#83]
Why are the students instructed to use RA_GRS replication on the storage account rather than LRS? The former is more expensive than the latter, and there doesn't seem to be any reason related to later labs as far as I recall from my previous run-through.

**Comment by ctesta-oneillmsft** [comment]
Simply because it is the default value. 

When using the official VM for the course they will get Azure credits so the cost should not be an issue for the individual. if you are using your own subscription then of course it will, and LRS will not impact the course/ I will not be changing this in the instructions as it is a directive that trainers can give
